/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Malloy Publisher - Semantic Model Serving API
 * The Malloy Publisher - Semantic Model Serving API provides comprehensive access to Malloy packages and their associated resources.
A Malloy package is a directory containing Malloy models (.malloy files), Malloy notebooks (.malloynb files), and embedded databases
(.parquet files) with a malloy-publisher.json manifest at the package's root directory.

## Key Features

- **Project Management**: Create and manage projects with their associated packages and connections
- **Package Lifecycle**: Full CRUD operations for Malloy packages and their versions
- **Model & Notebook Access**: Retrieve and execute Malloy models and notebooks
- **Connection Management**: Secure database connection configuration and testing
- **Query Execution**: Execute queries against models and retrieve results
- **Watch Mode**: Real-time file watching for development workflows

## Resource Hierarchy

The API follows a hierarchical resource structure:
```
Projects
├── Connections
└── Packages
    ├── Models
    ├── Notebooks
    └── Databases
```

For examples, see the Malloy samples packages (https://github.com/malloydata/malloy-samples) repository.

 * Service version: v0
 */
/**
 * Standard identifier pattern for resource names
 * @pattern ^[a-zA-Z0-9_-]+$
 */
export type IdentifierPattern = string;

/**
 * Version identifier pattern supporting dots and dashes
 * @pattern ^[a-zA-Z0-9_.-]+$
 */
export type VersionIdPattern = string;

/**
 * Path pattern supporting slashes, dots, and dashes
 * @pattern ^[a-zA-Z0-9_/.-]+$
 */
export type PathPattern = string;

/**
 * Current server status and health information
 */
export interface ServerStatus {
   /** Unix timestamp of the status check */
   timestamp?: number;
   /** List of available projects */
   projects?: Project[];
   /** Whether the server is fully initialized and ready to serve requests */
   initialized?: boolean;
   /** Whether the server configuration is frozen (read-only mode). When true, all mutation operations are disabled. */
   frozenConfig?: boolean;
}

/**
 * Represents a Malloy project containing packages, connections, and other resources
 */
export interface Project {
   /** Resource path to the project */
   resource?: string;
   /** Project name */
   name?: string;
   /** Project README content */
   readme?: string;
   /** Project location, can be an absolute path or URI (e.g. github, s3, gcs, etc.) */
   location?: string;
   /** List of database connections configured for this project */
   connections?: Connection[];
   /** List of Malloy packages in this project */
   packages?: Package[];
}

/**
 * Represents a Malloy package containing models, notebooks, and embedded databases
 */
export interface Package {
   /** Resource path to the package */
   resource?: string;
   /** Package name */
   name?: string;
   /** Package description */
   description?: string;
   /** Package location, can be an absolute path or URI (e.g. github, s3, gcs, etc.) */
   location?: string;
}

/**
 * Malloy model metadata and status information
 */
export interface Model {
   /** Resource path to the model */
   resource?: string;
   /** Name of the package containing this model */
   packageName?: string;
   /** Relative path to the model file within its package directory */
   path?: string;
   /** Error message if the model failed to compile or load */
   error?: string;
}

/**
 * Malloy notebook metadata and status information
 */
export interface Notebook {
   /** Resource path to the notebook */
   resource?: string;
   /** Name of the package containing this notebook */
   packageName?: string;
   /** Relative path to the notebook file within its package directory */
   path?: string;
   /** Error message if the notebook failed to compile or load */
   error?: string;
}

/**
 * Raw Malloy notebook with unexecuted cell contents
 */
export interface RawNotebook {
   /** Resource path to the notebook */
   resource?: string;
   /** Name of the package containing this notebook */
   packageName?: string;
   /** Relative path to the notebook file within its package directory */
   path?: string;
   /** Version of the Malloy compiler used to generate the notebook data */
   malloyVersion?: string;
   /** Array of notebook cells containing raw markdown and code content */
   notebookCells?: NotebookCell[];
   /** Array of file-level (##) annotations attached to the notebook */
   annotations?: string[];
}

/**
 * Compiled Malloy model with sources, queries, and metadata
 */
export interface CompiledModel {
   /** Resource path to the model */
   resource?: string;
   /** Name of the package containing this model */
   packageName?: string;
   /** Relative path to the model file within its package directory */
   path?: string;
   /** Version of the Malloy compiler used to generate the model data */
   malloyVersion?: string;
   /** JSON string containing model metadata and structure information */
   modelInfo?: string;
   /** Array of JSON strings containing source information for each data source */
   sourceInfos?: string[];
   /** Array of named queries defined in the model */
   queries?: Query[];
}

/**
 * Named model view definition
 */
export interface View {
   /** Name of the view */
   name?: string;
   /** Annotations attached to the view */
   annotations?: string[];
}

/**
 * Named model query definition
 */
export interface Query {
   /** Name of the query */
   name?: string;
   /** Name of the source this query operates on */
   sourceName?: string;
   /** Annotations attached to the query */
   annotations?: string[];
}

/**
 * Request body for executing a Malloy query
 */
export interface QueryRequest {
   /** Query string to execute on the model. If the query parameter is set, the queryName parameter must be empty. */
   query?: string;
   /** Name of the source in the model to use for queryName, search, and topValue requests. */
   sourceName?: string;
   /** Name of a query to execute on a source in the model. Requires the sourceName parameter is set. If the queryName parameter is set, the query parameter must be empty. */
   queryName?: string;
   /** Version ID */
   versionId?: string;
}

/**
 * Type of notebook cell
 */
export type NotebookCellType =
   (typeof NotebookCellType)[keyof typeof NotebookCellType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotebookCellType = {
   markdown: "markdown",
   code: "code",
} as const;

/**
 * Individual cell within a Malloy notebook
 */
export interface NotebookCell {
   /** Type of notebook cell */
   type?: NotebookCellType;
   /** Text contents of the notebook cell (either markdown or Malloy code) */
   text?: string;
   /** Array of JSON strings containing SourceInfo objects made available in this cell */
   newSources?: string[];
   /** JSON string containing QueryInfo object for the query in this cell (if the cell contains a query) */
   queryInfo?: string;
}

/**
 * Type of notebook cell
 */
export type NotebookCellResultType =
   (typeof NotebookCellResultType)[keyof typeof NotebookCellResultType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotebookCellResultType = {
   markdown: "markdown",
   code: "code",
} as const;

/**
 * Result of executing a notebook cell
 */
export interface NotebookCellResult {
   /** Type of notebook cell */
   type?: NotebookCellResultType;
   /** Text contents of the notebook cell */
   text?: string;
   /** JSON string containing the execution result for this cell */
   result?: string;
   /** Array of JSON strings containing SourceInfo objects made available in this cell */
   newSources?: string[];
}

/**
 * Results from executing a Malloy query
 */
export interface QueryResult {
   /** JSON string containing the query results, metadata, and execution information */
   result?: string;
   /** Resource path to the query result */
   resource?: string;
}

/**
 * Type of embedded database
 */
export type DatabaseType = (typeof DatabaseType)[keyof typeof DatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseType = {
   embedded: "embedded",
   materialized: "materialized",
} as const;

/**
 * Embedded database within a Malloy package
 */
export interface Database {
   /** Resource path to the database */
   resource?: string;
   /** Relative path to the database file within its package directory */
   path?: string;
   info?: TableDescription;
   /** Type of embedded database */
   type?: DatabaseType;
}

/**
 * A schema name in a Connection.
 */
export interface Schema {
   /** Name of the schema */
   name?: string;
   /** Description of the schema */
   description?: string;
   /** Whether this schema is the default schema */
   isDefault?: boolean;
   /** Whether this schema is hidden */
   isHidden?: boolean;
}

/**
 * Type of database connection
 */
export type ConnectionType =
   (typeof ConnectionType)[keyof typeof ConnectionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionType = {
   postgres: "postgres",
   bigquery: "bigquery",
   snowflake: "snowflake",
   trino: "trino",
   mysql: "mysql",
   duckdb: "duckdb",
   motherduck: "motherduck",
} as const;

/**
 * Database connection configuration and metadata
 */
export interface Connection {
   /** Resource path to the connection */
   resource?: string;
   /** Name of the connection */
   name?: string;
   /** Type of database connection */
   type?: ConnectionType;
   attributes?: ConnectionAttributes;
   postgresConnection?: PostgresConnection;
   bigqueryConnection?: BigqueryConnection;
   snowflakeConnection?: SnowflakeConnection;
   trinoConnection?: TrinoConnection;
   mysqlConnection?: MysqlConnection;
   duckdbConnection?: DuckdbConnection;
   motherduckConnection?: MotherDuckConnection;
}

/**
 * Connection capabilities and configuration attributes
 */
export interface ConnectionAttributes {
   /** SQL dialect name for the connection */
   dialectName?: string;
   /** Whether the connection uses connection pooling */
   isPool?: boolean;
   /** Whether the connection supports persistent storage operations */
   canPersist?: boolean;
   /** Whether the connection supports streaming query results */
   canStream?: boolean;
}

/**
 * PostgreSQL database connection configuration
 */
export interface PostgresConnection {
   /** PostgreSQL server hostname or IP address */
   host?: string;
   /** PostgreSQL server port number */
   port?: number;
   /** Name of the PostgreSQL database */
   databaseName?: string;
   /** PostgreSQL username for authentication */
   userName?: string;
   /** PostgreSQL password for authentication */
   password?: string;
   /** Complete PostgreSQL connection string (alternative to individual parameters) */
   connectionString?: string;
}

/**
 * MySQL database connection configuration
 */
export interface MysqlConnection {
   /** MySQL server hostname or IP address */
   host?: string;
   /** MySQL server port number */
   port?: number;
   /** Name of the MySQL database */
   database?: string;
   /** MySQL username for authentication */
   user?: string;
   /** MySQL password for authentication */
   password?: string;
}

/**
 * Google Cloud Storage connection configuration for DuckDB
 */
export interface GCSConnection {
   /** GCS HMAC access key ID */
   keyId: string;
   /** GCS HMAC secret key */
   secret: string;
}

/**
 * AWS S3 connection configuration for DuckDB
 */
export interface S3Connection {
   /** AWS access key ID */
   accessKeyId: string;
   /** AWS secret access key */
   secretAccessKey: string;
   /** AWS region (e.g., us-east-1) */
   region?: string;
   /** Custom S3-compatible endpoint URL (optional, for MinIO, etc.) */
   endpoint?: string;
   /** AWS session token for temporary credentials (optional) */
   sessionToken?: string;
}

/**
 * Google BigQuery database connection configuration
 */
export interface BigqueryConnection {
   /** Default BigQuery project ID for queries */
   defaultProjectId?: string;
   /** BigQuery project ID for billing purposes */
   billingProjectId?: string;
   /** BigQuery dataset location/region */
   location?: string;
   /** JSON string containing Google Cloud service account credentials */
   serviceAccountKeyJson?: string;
   /** Maximum bytes to bill for query execution (prevents runaway costs) */
   maximumBytesBilled?: string;
   /** Query timeout in milliseconds */
   queryTimeoutMilliseconds?: string;
}

/**
 * Snowflake database connection configuration
 */
export interface SnowflakeConnection {
   /** Snowflake account identifier */
   account?: string;
   /** Snowflake username for authentication */
   username?: string;
   /** Snowflake password for authentication */
   password?: string;
   /** Snowflake private key for authentication */
   privateKey?: string;
   /** Passphrase for the Snowflake private key */
   privateKeyPass?: string;
   /** Snowflake warehouse name */
   warehouse?: string;
   /** Snowflake database name */
   database?: string;
   /** Snowflake schema name */
   schema?: string;
   /** Snowflake role name */
   role?: string;
   /** Query response timeout in milliseconds */
   responseTimeoutMilliseconds?: number;
}

/**
 * Trino database connection configuration
 */
export interface TrinoConnection {
   /** Trino server hostname or IP address */
   server?: string;
   /** Trino server port number */
   port?: number;
   /** Trino catalog name */
   catalog?: string;
   /** Trino schema name */
   schema?: string;
   /** Trino username for authentication */
   user?: string;
   /** Trino password for authentication */
   password?: string;
   /** Peaka API key for authentication with Peaka-hosted Trino clusters */
   peakaKey?: string;
}

/**
 * MotherDuck database connection configuration
 */
export interface MotherDuckConnection {
   /** MotherDuck access token */
   accessToken?: string;
   /** MotherDuck database name */
   database?: string;
}

/**
 * DuckDB database connection configuration
 */
export interface DuckdbConnection {
   attachedDatabases?: AttachedDatabase[];
}

/**
 * Type of database connection
 */
export type AttachedDatabaseType =
   (typeof AttachedDatabaseType)[keyof typeof AttachedDatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttachedDatabaseType = {
   bigquery: "bigquery",
   snowflake: "snowflake",
   postgres: "postgres",
   gcs: "gcs",
   s3: "s3",
} as const;

/**
 * Attached DuckDB database
 */
export interface AttachedDatabase {
   /** @pattern ^[a-zA-Z_][a-zA-Z0-9_]*$ */
   name?: string;
   /** Type of database connection */
   type?: AttachedDatabaseType;
   attributes?: ConnectionAttributes;
   bigqueryConnection?: BigqueryConnection;
   snowflakeConnection?: SnowflakeConnection;
   postgresConnection?: PostgresConnection;
   gcsConnection?: GCSConnection;
   s3Connection?: S3Connection;
}

export interface SqlSource {
   /** Resource path to the sql source. */
   resource?: string;
   source?: string;
}

export interface Table {
   /** Resource path to the table. */
   resource?: string;
   /** Table source as a JSON string. */
   source?: string;
   /** Table fields */
   columns?: Column[];
}

/**
 * @deprecated
 */
export interface TableSource {
   /** Resource path to the table source. */
   resource?: string;
   source?: string;
   /** Table fields */
   columns?: Column[];
}

export interface TemporaryTable {
   /** Resource path to the temporary table. */
   resource?: string;
   table?: string;
}

export interface QueryData {
   /** Resource path to the query data. */
   resource?: string;
   data?: string;
}

/**
 * Standard error response format
 */
export interface Error {
   /** Human-readable error message describing what went wrong */
   message: string;
   /** Additional error details or context */
   details?: string;
}

/**
 * Database column definition
 */
export interface Column {
   /** Name of the column */
   name?: string;
   /** Data type of the column */
   type?: string;
}

/**
 * Database table structure and metadata
 */
export interface TableDescription {
   /** Name of the table */
   name?: string;
   /** Number of rows in the table */
   rowCount?: number;
   /** List of columns in the table */
   columns?: Column[];
}

/**
 * Current file watching status and configuration
 */
export interface WatchStatus {
   /** Whether file watching is currently active */
   enabled?: boolean;
   /** Name of the project being watched for file changes */
   projectName?: string;
   /**
    * The file system path being monitored for changes, null if not watching
    * @nullable
    */
   watchingPath?: string | null;
}

/**
 * Request to start file watching for a project
 */
export interface StartWatchRequest {
   /** Name of the project to start watching for file changes */
   projectName: string;
}

/**
 * Connection test result status
 */
export type ConnectionStatusStatus =
   (typeof ConnectionStatusStatus)[keyof typeof ConnectionStatusStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConnectionStatusStatus = {
   ok: "ok",
   failed: "failed",
} as const;

/**
 * Result of testing a database connection
 */
export interface ConnectionStatus {
   /** Connection test result status */
   status?: ConnectionStatusStatus;
   /** Error message if the connection test failed, null if successful */
   errorMessage?: string;
}

/**
 * The request was malformed or cannot be performed given the current state of the system
 */
export type BadRequestResponse = Error;

/**
 * Unauthorized - authentication required
 */
export type UnauthorizedResponse = Error;

/**
 * Forbidden - insufficient permissions to perform the operation
 */
export type ForbiddenResponse = Error;

/**
 * The specified resource was not found
 */
export type NotFoundResponse = Error;

/**
 * The server encountered an internal error
 */
export type InternalServerErrorResponse = Error;

/**
 * The requested operation is not implemented
 */
export type NotImplementedResponse = Error;

/**
 * Model compilation failed due to syntax or semantic errors
 */
export type ModelCompilationErrorResponse = Error;

export type GetProjectParams = {
   /**
    * Load / reload the project before returning result
    */
   reload?: boolean;
};

export type CreateConnection201 = {
   message?: string;
};

export type CreateConnection409 = {
   error?: string;
};

export type UpdateConnectionBody = {
   postgresConnection?: PostgresConnection;
   mysqlConnection?: MysqlConnection;
   bigqueryConnection?: BigqueryConnection;
   snowflakeConnection?: SnowflakeConnection;
   duckdbConnection?: DuckdbConnection;
   motherduckConnection?: MotherDuckConnection;
   trinoConnection?: TrinoConnection;
};

export type UpdateConnection200 = {
   message?: string;
};

export type DeleteConnection200 = {
   message?: string;
};

export type GetSqlsourceParams = {
   /**
    * SQL statement
    */
   sqlStatement?: string;
};

export type PostSqlsourceBody = {
   sqlStatement?: string;
};

export type PostQuerydataParams = {
   /**
    * Options
    */
   options?: string;
};

export type PostQuerydataBody = {
   sqlStatement?: string;
};

export type PostTemporarytableBody = {
   sqlStatement?: string;
};

export type GetTemporarytableParams = {
   /**
    * SQL statement
    */
   sqlStatement?: string;
};

export type GetTablesourceParams = {
   /**
    * Table key
    */
   tableKey?: string;
   /**
    * Table path
    */
   tablePath?: string;
};

export type GetQuerydataParams = {
   /**
    * SQL statement
    */
   sqlStatement?: string;
   /**
    * Options
    */
   options?: string;
};

export type GetPackageParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
   /**
    * Load / reload the package before returning result
    */
   reload?: boolean;
};

export type ListModelsParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};

export type GetModelParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};

export type ListNotebooksParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};

export type GetNotebookParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};

export type ExecuteNotebookCellParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};

export type ListDatabasesParams = {
   /**
    * Version identifier for the package
    */
   versionId?: VersionIdPattern;
};
