/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Malloy Publisher - Semantic Model Serving API
 * The Malloy Publisher - Semantic Model Serving API provides comprehensive access to Malloy packages and their associated resources.
A Malloy package is a directory containing Malloy models (.malloy files), Malloy notebooks (.malloynb files), and embedded databases
(.parquet files) with a malloy-publisher.json manifest at the package's root directory.

## Key Features

- **Project Management**: Create and manage projects with their associated packages and connections
- **Package Lifecycle**: Full CRUD operations for Malloy packages and their versions
- **Model & Notebook Access**: Retrieve and execute Malloy models and notebooks
- **Connection Management**: Secure database connection configuration and testing
- **Query Execution**: Execute queries against models and retrieve results
- **Watch Mode**: Real-time file watching for development workflows

## Resource Hierarchy

The API follows a hierarchical resource structure:
```
Projects
├── Connections
└── Packages
    ├── Models
    ├── Notebooks
    └── Databases
```

For examples, see the Malloy samples packages (https://github.com/malloydata/malloy-samples) repository.

 * Service version: v0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import * as http from "k6/http";
import type { Params, Response } from "k6/http";

import type {
   CompiledModel,
   GetModelParams,
   IdentifierPattern,
   ListModelsParams,
   Model,
   PathPattern,
   QueryRequest,
   QueryResult,
   VersionIdPattern,
} from "./malloyPublisherSemanticModelServingAPI.schemas";

/**
 * This is the base client to use for interacting with the API.
 */
export class ModelsClient {
   private cleanBaseUrl: string;
   private commonRequestParameters: Params;

   constructor(clientOptions: {
      baseUrl: string;
      commonRequestParameters?: Params;
   }) {
      this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

      this.commonRequestParameters =
         clientOptions.commonRequestParameters || {};
   }

   /**
 * Retrieves a list of all Malloy models within the specified package. Each model entry
includes the relative path, package name, and any compilation errors. This endpoint
is useful for discovering available models and checking their status.

 * @summary List package models
 */
   listModels(
      projectName: IdentifierPattern,
      packageName: IdentifierPattern,
      params?: ListModelsParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Model[];
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/models` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Retrieves a compiled Malloy model with its source information, queries, and metadata.
The model is compiled using the specified version of the Malloy compiler. This endpoint
provides access to the model's structure, sources, and named queries for use in applications.

 * @summary Get compiled Malloy model
 */
   getModel(
      projectName: IdentifierPattern,
      packageName: string,
      path: PathPattern,
      params?: GetModelParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: CompiledModel;
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/models/${path}` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Executes a Malloy query against a model and returns the results. The query can be specified
as a raw Malloy query string or by referencing a named query within the model. This endpoint
supports both ad-hoc queries and predefined model queries, making it flexible for various
use cases including data exploration, reporting, and application integration.

 * @summary Execute Malloy query
 */
   executeQueryModel(
      projectName: IdentifierPattern,
      packageName: VersionIdPattern,
      path: PathPattern,
      queryRequest: QueryRequest,
      requestParameters?: Params,
   ): {
      response: Response;
      data: QueryResult;
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/models/${path}/query`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request(
         "POST",
         url.toString(),
         JSON.stringify(queryRequest),
         {
            ...mergedRequestParameters,
            headers: {
               ...mergedRequestParameters?.headers,
               "Content-Type": "application/json",
            },
         },
      );
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }

   /**
    * Merges the provided request parameters with default parameters for the client.
    *
    * @param {Params} requestParameters - The parameters provided specifically for the request
    * @param {Params} commonRequestParameters - Common parameters for all requests
    * @returns {Params} - The merged parameters
    */
   private _mergeRequestParameters(
      requestParameters?: Params,
      commonRequestParameters?: Params,
   ): Params {
      return {
         ...commonRequestParameters, // Default to common parameters
         ...requestParameters, // Override with request-specific parameters
         headers: {
            ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
            ...(requestParameters?.headers || {}),
         },
         cookies: {
            ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
            ...(requestParameters?.cookies || {}),
         },
         tags: {
            ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
            ...(requestParameters?.tags || {}),
         },
      };
   }
}
