/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Malloy Publisher - Semantic Model Serving API
 * The Malloy Publisher - Semantic Model Serving API provides comprehensive access to Malloy packages and their associated resources.
A Malloy package is a directory containing Malloy models (.malloy files), Malloy notebooks (.malloynb files), and embedded databases
(.parquet files) with a malloy-publisher.json manifest at the package's root directory.

## Key Features

- **Project Management**: Create and manage projects with their associated packages and connections
- **Package Lifecycle**: Full CRUD operations for Malloy packages and their versions
- **Model & Notebook Access**: Retrieve and execute Malloy models and notebooks
- **Connection Management**: Secure database connection configuration and testing
- **Query Execution**: Execute queries against models and retrieve results
- **Watch Mode**: Real-time file watching for development workflows

## Resource Hierarchy

The API follows a hierarchical resource structure:
```
Projects
├── Connections
└── Packages
    ├── Models
    ├── Notebooks
    └── Databases
```

For examples, see the Malloy samples packages (https://github.com/malloydata/malloy-samples) repository.

 * Service version: v0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import * as http from "k6/http";
import type { Params, Response } from "k6/http";

import type {
   ExecuteNotebookCellParams,
   GetNotebookParams,
   IdentifierPattern,
   ListNotebooksParams,
   Notebook,
   NotebookCellResult,
   RawNotebook,
} from "./malloyPublisherSemanticModelServingAPI.schemas";

/**
 * This is the base client to use for interacting with the API.
 */
export class NotebooksClient {
   private cleanBaseUrl: string;
   private commonRequestParameters: Params;

   constructor(clientOptions: {
      baseUrl: string;
      commonRequestParameters?: Params;
   }) {
      this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

      this.commonRequestParameters =
         clientOptions.commonRequestParameters || {};
   }

   /**
 * Retrieves a list of all Malloy notebooks within the specified package. Each notebook entry
includes the relative path, package name, and any compilation errors. This endpoint
is useful for discovering available notebooks and checking their status.

 * @summary List package notebooks
 */
   listNotebooks(
      projectName: IdentifierPattern,
      packageName: IdentifierPattern,
      params?: ListNotebooksParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Notebook[];
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/notebooks` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Retrieves a Malloy notebook with its raw cell contents (markdown and code).
Cell execution should be done separately via the execute-notebook-cell endpoint.

 * @summary Get Malloy notebook cells
 */
   getNotebook(
      projectName: IdentifierPattern,
      packageName: string,
      path: string,
      params?: GetNotebookParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: RawNotebook;
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/notebooks/${path}` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Executes a specific cell in a Malloy notebook by index. For code cells, this compiles
and runs the Malloy code, returning query results and any new sources defined.
For markdown cells, this simply returns the cell content.

 * @summary Execute a specific notebook cell
 */
   executeNotebookCell(
      projectName: IdentifierPattern,
      packageName: string,
      path: string,
      cellIndex: number,
      params?: ExecuteNotebookCellParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: NotebookCellResult;
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}/packages/${packageName}/notebooks/${path}/cells/${cellIndex}` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }

   /**
    * Merges the provided request parameters with default parameters for the client.
    *
    * @param {Params} requestParameters - The parameters provided specifically for the request
    * @param {Params} commonRequestParameters - Common parameters for all requests
    * @returns {Params} - The merged parameters
    */
   private _mergeRequestParameters(
      requestParameters?: Params,
      commonRequestParameters?: Params,
   ): Params {
      return {
         ...commonRequestParameters, // Default to common parameters
         ...requestParameters, // Override with request-specific parameters
         headers: {
            ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
            ...(requestParameters?.headers || {}),
         },
         cookies: {
            ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
            ...(requestParameters?.cookies || {}),
         },
         tags: {
            ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
            ...(requestParameters?.tags || {}),
         },
      };
   }
}
