/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Malloy Publisher - Semantic Model Serving API
 * The Malloy Publisher - Semantic Model Serving API provides comprehensive access to Malloy packages and their associated resources.
A Malloy package is a directory containing Malloy models (.malloy files), Malloy notebooks (.malloynb files), and embedded databases
(.parquet files) with a malloy-publisher.json manifest at the package's root directory.

## Key Features

- **Project Management**: Create and manage projects with their associated packages and connections
- **Package Lifecycle**: Full CRUD operations for Malloy packages and their versions
- **Model & Notebook Access**: Retrieve and execute Malloy models and notebooks
- **Connection Management**: Secure database connection configuration and testing
- **Query Execution**: Execute queries against models and retrieve results
- **Watch Mode**: Real-time file watching for development workflows

## Resource Hierarchy

The API follows a hierarchical resource structure:
```
Projects
├── Connections
└── Packages
    ├── Models
    ├── Notebooks
    └── Databases
```

For examples, see the Malloy samples packages (https://github.com/malloydata/malloy-samples) repository.

 * Service version: v0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import * as http from "k6/http";
import type { Params, Response } from "k6/http";

import type {
   GetProjectParams,
   IdentifierPattern,
   Project,
} from "./malloyPublisherSemanticModelServingAPI.schemas";

/**
 * This is the base client to use for interacting with the API.
 */
export class ProjectsClient {
   private cleanBaseUrl: string;
   private commonRequestParameters: Params;

   constructor(clientOptions: {
      baseUrl: string;
      commonRequestParameters?: Params;
   }) {
      this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

      this.commonRequestParameters =
         clientOptions.commonRequestParameters || {};
   }

   /**
 * Retrieves a list of all projects currently hosted on this Malloy Publisher server.
Each project contains metadata about its packages, connections, and configuration.
This endpoint is typically used to discover available projects and their basic information.

 * @summary List all available projects
 */
   listProjects(requestParameters?: Params): {
      response: Response;
      data: Project[];
   } {
      const url = new URL(this.cleanBaseUrl + `/projects`);
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request(
         "GET",
         url.toString(),
         undefined,
         mergedRequestParameters,
      );
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Creates a new Malloy project with the specified configuration. A project serves as a
container for packages, connections, and other resources. The project will be initialized
with the provided metadata and can immediately accept packages and connections.

 * @summary Create a new project
 */
   createProject(
      project: Project,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Project;
   } {
      const url = new URL(this.cleanBaseUrl + `/projects`);
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request(
         "POST",
         url.toString(),
         JSON.stringify(project),
         {
            ...mergedRequestParameters,
            headers: {
               ...mergedRequestParameters?.headers,
               "Content-Type": "application/json",
            },
         },
      );
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Retrieves detailed information about a specific project, including its packages,
connections, configuration, and metadata. The reload parameter can be used to
refresh the project state from disk before returning the information.

 * @summary Get project details and metadata
 */
   getProject(
      projectName: IdentifierPattern,
      params?: GetProjectParams,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Project;
   } {
      const url = new URL(
         this.cleanBaseUrl +
            `/projects/${projectName}` +
            `?${new URLSearchParams(params).toString()}`,
      );
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request("GET", url.toString(), undefined, {
         ...mergedRequestParameters,
      });
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Updates the configuration and metadata of an existing project. This allows you to
modify project settings, update the README, change the location, or update other
project-level properties. The project must exist and be accessible.

 * @summary Update project configuration
 */
   updateProject(
      projectName: IdentifierPattern,
      project: Project,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Project;
   } {
      const url = new URL(this.cleanBaseUrl + `/projects/${projectName}`);
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request(
         "PATCH",
         url.toString(),
         JSON.stringify(project),
         {
            ...mergedRequestParameters,
            headers: {
               ...mergedRequestParameters?.headers,
               "Content-Type": "application/json",
            },
         },
      );
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }
   /**
 * Permanently deletes a project and all its associated resources including packages,
connections, and metadata. This operation cannot be undone, so use with caution.
The project must exist and be accessible for deletion.

 * @summary Delete a project
 */
   deleteProject(
      projectName: IdentifierPattern,
      requestParameters?: Params,
   ): {
      response: Response;
      data: Project;
   } {
      const url = new URL(this.cleanBaseUrl + `/projects/${projectName}`);
      const mergedRequestParameters = this._mergeRequestParameters(
         requestParameters || {},
         this.commonRequestParameters,
      );
      const response = http.request(
         "DELETE",
         url.toString(),
         undefined,
         mergedRequestParameters,
      );
      let data;

      try {
         data = response.json();
      } catch {
         data = response.body;
      }
      return {
         response,
         data,
      };
   }

   /**
    * Merges the provided request parameters with default parameters for the client.
    *
    * @param {Params} requestParameters - The parameters provided specifically for the request
    * @param {Params} commonRequestParameters - Common parameters for all requests
    * @returns {Params} - The merged parameters
    */
   private _mergeRequestParameters(
      requestParameters?: Params,
      commonRequestParameters?: Params,
   ): Params {
      return {
         ...commonRequestParameters, // Default to common parameters
         ...requestParameters, // Override with request-specific parameters
         headers: {
            ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
            ...(requestParameters?.headers || {}),
         },
         cookies: {
            ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
            ...(requestParameters?.cookies || {}),
         },
         tags: {
            ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
            ...(requestParameters?.tags || {}),
         },
      };
   }
}
